# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Nerja Casa Tjeme"
license = "MIT"
licenselink = "https://github.com/kishaningithub/hugo-shopping-product-catalogue-simple/blob/master/LICENSE.md"
description = "Kishan B"
homepage = "https://github.com/kishaningithub"
tags = ["house", "real estate", "minimal", "responsive"]
features = ["catalogue", "bootstrap", "responsive"]
min_version = "0.38"

[author]
  name = "Raul B"
  homepage = "https://github.com/ideas24h"

# If porting an existing theme
[original]
  name = "Shopping Product Catalogue - Simple"
  homepage = "https://github.com/kishaningithub"
  repo = "https://github.com/kishaningithub/hugo-shopping-product-catalogue-simple"